MODULES = [
    (1, "dashboard", "Dashboard", "gerencial"),
    (2, "vendas", "Vendas", "operacional"),
    (3, "metas_cotas", "Metas e Cotas", "operacional"),
    (4, "faturamento", "Faturamento", "financeiro"),
    (7, "metricas", "Métricas", "gerencial"),
    (10, "usuarios", "Usuários", "administrativo"),
    (11, "configuracoes", "Configurações", "administrativo"),
    (12, "auditoria", "Auditoria", "administrativo"),
    (13, "financeiro", "Financeiro", "financeiro"),
    (14, "produto", "Produto", "operacional"),
    (15, "regras", "Motor de Regras", "operacional"),
    (16, "compras", "Compras", "operacional"),
    (17, "gerador_cotas", "Gerador de Cotas", "operacional"),
    (18, "prev_receber", "Prev. a Receber", "financeiro"),
    (19, "gerador_compras", "Gerador de Pedidos", "operacional"),
]

FUNCTIONS = [
    (3, 2, "vendas_por_vendedor", "Detalhe por vendedor"),
    (5, 2, "vendas_lancar", "Lançar venda manual"),
    (6, 3, "cotas_gerar", "Gerar cotas"),
    (7, 3, "cotas_editar", "Editar cotas"),
    (19, 10, "usuarios_criar", "Criar usuário"),
    (20, 10, "usuarios_editar", "Editar usuário"),
    (21, 10, "usuarios_desativar", "Desativar usuário"),
    (22, 10, "tipos_acesso_gerenciar", "Gerenciar tipos de acesso"),
    (25, 13, "financeiro_visualizar", "Visualizar financeiro"),
    (26, 14, "produto_visualizar", "Visualizar produtos"),
    (27, 14, "produto_editar", "Editar produtos"),
    (28, 15, "regras_gerenciar", "Gerenciar regras"),
    (29, 16, "compras_gerenciar", "Gerenciar compras"),
    (30, 17, "cotas_gerenciar", "Gerar e editar cotas"),
    (31, 18, "prev_receber_gerenciar", "Gerenciar previsão a receber"),
    (32, 19, "ped_compras_criar", "Criar pedido de compra"),
]

REPORTS = [
    (1, 1, "rel_kpi_diario", "KPIs Diários"),
    (2, 1, "rel_ranking_lojas", "Ranking de Lojas"),
    (3, 2, "rel_vendas_periodo", "Vendas por Período"),
    (4, 2, "rel_vendas_vendedor", "Performance por Vendedor"),
    (5, 2, "rel_vendas_comparativo_ly", "Comparativo Ano Anterior"),
    (6, 2, "rel_vendas_exportavel", "Exportação de Vendas"),
    (7, 3, "rel_atingimento_mensal", "Atingimento Mensal"),
    (8, 3, "rel_projecao_fechamento", "Projeção de Fechamento"),
    (9, 3, "rel_curva_diaria", "Curva Diária"),
    (10, 4, "rel_faturamento_mensal", "Faturamento Mensal"),
    (11, 4, "rel_margem_contribuicao", "Margem de Contribuição"),
    (17, 12, "rel_log_acessos", "Log de Acessos"),
    (18, 12, "rel_permissoes_usuarios", "Permissões por Usuário"),
    (20, 14, "rel_produtos_catalogo", "Catálogo de Produtos"),
    (21, 14, "rel_produtos_precificacao", "Relatório de Precificação"),
    (22, 16, "rel_compras_pedidos", "Pedidos de Compra"),
    (23, 17, "rel_cotas_historico", "Histórico de Cotas"),
    (24, 18, "rel_prev_receber", "Previsão a Receber"),
    (25, 19, "rel_ped_compras_historico", "Histórico de Pedidos"),
]

STORES = [
    (1, "LFSP PATIO PAULISTA", "São Paulo", "SP", True),
    (2, "LFSP IG CAMPINAS", "Campinas", "SP", True),
    (3, "LFSP ELDORADO", "São Paulo", "SP", True),
    (4, "LFSP MOOCA", "São Paulo", "SP", True),
    (5, "LFSP PARK SAO CAETANO", "São Caetano do Sul", "SP", True),
    (6, "LFSP BOURBON", "São Paulo", "SP", True),
    (7, "LFSP E-COMMERCE", "São Paulo", "SP", True),
    (8, "LFSP OUTLET GR SAO PAULO", "Itaquaquecetuba", "SP", True),
    (9, "LFSP OUTLET CATARINA", "São Roque", "SP", True),
    (10, "LFSP JARDIM SUL", "São Paulo", "SP", True),
    (11, "LFSP UNIAO DE OSASCO", "Osasco", "SP", True),
    (12, "LFSP PIRACICABA", "Piracicaba", "SP", True),
    (13, "LFSP ESPLANADA", "Votorantim", "SP", False),
    (14, "LFSP GRAND PLAZA", "Santo André", "SP", False),
    (15, "LFSP ABC", "Santo André", "SP", True),
    (16, "LFSP TAMBORE", "Barueri", "SP", True),
    (17, "LFSP OUTLET ITUPEVA", "Itupeva", "SP", True),
    (18, "LFSP OUTLET IMIGRANTES", "São Bernardo do Campo", "SP", True),
    (100, "AAA CATUAI", "Londrina", "PR", True),
    (101, "CA IBIRAPUERA", "São Paulo", "SP", False),
    (102, "CNS CENTER NORTE", "São Paulo", "SP", True),
    (105, "LGD MUELLER", "Curitiba", "PR", True),
    (106, "MAM PARK BARIGUI", "Curitiba", "PR", True),
    (107, "MC IG PORTO ALEGRE", "Porto Alegre", "RS", True),
    (108, "ML OUTLET BRASILIA", "Alexânia", "GO", True),
    (109, "PMB DOM PEDRO", "Campinas", "SP", True),
    (110, "VIVIRL RECIFE", "Recife", "PE", False),
    (111, "AA PARK JUNDIAI", "Jundiaí", "SP", True),
    (112, "LS OUTLET NOVO HAMBURGO", "Novo Hamburgo", "RS", True),
    (123, "GRF FLAMBOYANT", "Goiânia", "GO", False),
    (125, "DAC FLAMBOYANT", "Goiânia", "GO", False),
    (126, "CNS IBIRAPUERA", "São Paulo", "SP", True),
    (127, "GRA FLAMBOYANT", "Goiânia", "GO", True),
]

ACCESS_TYPES = [
    (
        1,
        "Acesso Completo",
        "Super Admin — acesso irrestrito",
        "#ef4444",
        "all",
        "all",
        "all",
    ),
    (
        2,
        "Supervisão Geral",
        "Visibilidade total do grupo",
        "#7c3aed",
        [1, 2, 3, 7, 14, 17, 18],
        [3, 6, 7, 26, 30, 31],
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 23, 24],
    ),
    (
        3,
        "Supervisão Regional",
        "Acompanhamento regional",
        "#f59e0b",
        [1, 2, 3, 7],
        [3, 7],
        [1, 2, 3, 4, 7, 8, 9],
    ),
    (
        4,
        "Acesso Financeiro",
        "Financeiro e fluxo de caixa",
        "#10b981",
        [1, 4, 7, 13],
        [25],
        [1, 2, 10, 11],
    ),
    (
        5,
        "Acesso Comercial",
        "Vendas, metas, compras e produtos",
        "#f97316",
        [1, 2, 3, 7, 14, 16, 17],
        [3, 6, 7, 26, 27, 29, 30],
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 22, 23],
    ),
    (
        6,
        "Operação Loja",
        "Operação diária da loja",
        "#3b82f6",
        [1, 2, 3, 7],
        [3, 5, 7],
        [1, 3, 7, 8, 9],
    ),
    (
        7,
        "Administrativo",
        "Usuários, perfis e configurações",
        "#64748b",
        [1, 10, 11, 12],
        [19, 20, 21, 22],
        [1, 2, 17, 18],
    ),
    (8, "PDV Loja", "Perfil padrão do PDV", "#2dbf7e", "all", "all", "all"),
    (
        9,
        "Gestão de Compras",
        "Compras, produtos e fornecedores",
        "#0ea5e9",
        [1, 14, 16, 19],
        [26, 27, 29, 32],
        [1, 20, 21, 22, 25],
    ),
    (
        10,
        "Motor de Regras",
        "Gestão de regras automáticas",
        "#8b5cf6",
        [1, 15],
        [28],
        [1, 2],
    ),
    (
        11,
        "Gerador de Cotas",
        "Geração e edição de cotas",
        "#06b6d4",
        [1, 3, 17],
        [6, 7, 30],
        [1, 7, 8, 9, 23],
    ),
    (
        12,
        "Prev. a Receber",
        "Previsão de recebimento",
        "#14b8a6",
        [1, 18],
        [31],
        [1, 24],
    ),
    (
        13,
        "Gerador de Pedidos",
        "Gestão de pedidos de compra",
        "#f59e0b",
        [1, 16, 19],
        [29, 32],
        [1, 22, 25],
    ),
]

PDV_USERS = [
    (3, "cnspatiopaulista@cnsonline.com.br"),
    (4, "cnsigcampinas@cnsonline.com.br"),
    (5, "cnseldorado@cnsonline.com.br"),
    (6, "cnsmooca@cnsonline.com.br"),
    (7, "cnsparksaocaetano@cnsonline.com.br"),
    (8, "cnsbourbon@cnsonline.com.br"),
    (9, "cnsecommerce@cnsonline.com.br"),
    (10, "cnsoutletgrandesp@cnsonline.com.br"),
    (11, "cnsoutletcatarina@cnsonline.com.br"),
    (12, "cnsjardimsul@cnsonline.com.br"),
    (13, "cnsuniaodeosasco@cnsonline.com.br"),
    (14, "cnspiracicaba@cnsonline.com.br"),
    (15, "cnsesplanada@cnsonline.com.br"),
    (16, "cnsgrandplaza@cnsonline.com.br"),
    (17, "cnsabc@cnsonline.com.br"),
    (18, "cnstambore@cnsonline.com.br"),
    (19, "cnsoutletitupeva@cnsonline.com.br"),
    (20, "cnsoutletimigrantes@cnsonline.com.br"),
    (21, "cnscatuai@cnsonline.com.br"),
    (22, "cnsibirapuera101@cnsonline.com.br"),
    (23, "cnscenternorte@cnsonline.com.br"),
    (24, "cnsmueller@cnsonline.com.br"),
    (25, "cnsparkbarigui@cnsonline.com.br"),
    (26, "cnsigportoalegre@cnsonline.com.br"),
    (27, "cnsoutletbrasilia@cnsonline.com.br"),
    (28, "cnsdompedro@cnsonline.com.br"),
    (29, "cnsrecife@cnsonline.com.br"),
    (30, "cnsparkjundiai@cnsonline.com.br"),
    (31, "cnsoutletplatinum@cnsonline.com.br"),
    (32, "cnsflamboyant123@cnsonline.com.br"),
    (33, "cnsflamboyant125@cnsonline.com.br"),
    (34, "cnsibirapuera126@cnsonline.com.br"),
    (35, "cnsflamboyant127@cnsonline.com.br"),
]

SUPER_ADMINS = [
    ("Lázaro de Macêdo", "lazaro@cnsonline.com.br"),
    ("Afonso Tarsitano", "afonso@cnsonline.com.br"),
]
