"""cria modulo de usuarios e rbac

Revision ID: e33db93311c9
Revises:
Create Date: 2026-06-19 21:01:11.184668
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e33db93311c9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lojas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("cidade", sa.String(length=100), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_id"),
    )
    op.create_table(
        "modulos_catalogo",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=80), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("categoria", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
        sa.UniqueConstraint("legacy_id"),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("codigo", sa.String(length=100), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "tipos_acesso",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_id", sa.Integer(), nullable=True),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("nome_normalizado", sa.String(length=120), nullable=False),
        sa.Column("descricao", sa.String(length=500), nullable=True),
        sa.Column("cor", sa.String(length=20), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("sistema", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("legacy_id"),
        sa.UniqueConstraint("nome_normalizado"),
    )
    op.create_table(
        "funcs_catalogo",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_id", sa.Integer(), nullable=False),
        sa.Column("modulo_id", sa.String(length=36), nullable=False),
        sa.Column("codigo", sa.String(length=100), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["modulo_id"],
            ["modulos_catalogo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
        sa.UniqueConstraint("legacy_id"),
    )
    op.create_table(
        "rels_catalogo",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("legacy_id", sa.Integer(), nullable=False),
        sa.Column("modulo_id", sa.String(length=36), nullable=False),
        sa.Column("codigo", sa.String(length=100), nullable=False),
        sa.Column("nome", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["modulo_id"],
            ["modulos_catalogo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
        sa.UniqueConstraint("legacy_id"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("tipo_acesso_id", sa.String(length=36), nullable=False),
        sa.Column("permission_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tipo_acesso_id"], ["tipos_acesso.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tipo_acesso_id", "permission_id"),
    )
    op.create_table(
        "tipos_acesso_modulos",
        sa.Column("tipo_acesso_id", sa.String(length=36), nullable=False),
        sa.Column("modulo_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["modulo_id"], ["modulos_catalogo.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tipo_acesso_id"], ["tipos_acesso.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tipo_acesso_id", "modulo_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "super_admin",
                "supervisao_geral",
                "supervisao_regional",
                "loja",
                "pdv",
                "financeiro",
                "compras",
                "rh_pessoal",
                "administrativo",
                "gerador_cotas",
                "prev_receber",
                "gerador_compras",
                name="tipo_usuario",
            ),
            nullable=False,
        ),
        sa.Column("cargo", sa.String(length=100), nullable=True),
        sa.Column("nivel", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("force_password_change", sa.Boolean(), nullable=False),
        sa.Column("loja_id", sa.String(length=36), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["loja_id"],
            ["lojas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_nome", "users", ["nome"], unique=False)
    op.create_index("ix_users_tipo_ativo", "users", ["tipo", "ativo"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index(
        "ix_refresh_tokens_user_active",
        "refresh_tokens",
        ["user_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "tipos_acesso_relatorios",
        sa.Column("tipo_acesso_id", sa.String(length=36), nullable=False),
        sa.Column("relatorio_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["relatorio_id"], ["rels_catalogo.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tipo_acesso_id"], ["tipos_acesso.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tipo_acesso_id", "relatorio_id"),
    )
    op.create_table(
        "users_tipos_acesso",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("tipo_acesso_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["tipo_acesso_id"], ["tipos_acesso.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "tipo_acesso_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_tipos_acesso")
    op.drop_table("tipos_acesso_relatorios")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_users_tipo_ativo", table_name="users")
    op.drop_index("ix_users_nome", table_name="users")
    op.drop_table("users")
    op.drop_table("tipos_acesso_modulos")
    op.drop_table("role_permissions")
    op.drop_table("rels_catalogo")
    op.drop_table("funcs_catalogo")
    op.drop_table("tipos_acesso")
    op.drop_table("permissions")
    op.drop_table("modulos_catalogo")
    op.drop_table("lojas")
    # ### end Alembic commands ###
